[phases.setup]
nixPkgs = ["python311", "gcc", "g++"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Enhanced chatbot build completed'",
  "echo 'Working directory:' && pwd",
  "echo 'Contents:' && ls -la"
]

[start]
cmd = "python app.py"
